name: Package

on:
  push:
    branches:
      - master

env:    
  AWS_S3_UPLOAD_SESSION: gh-action-session-zbrowio
  AWS_S3_UPLOAD_REGION: us-east-1
  AWS_S3_UPLOAD_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ghactions-zbrowio-s3-upload

jobs:
  package-static-content:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_S3_UPLOAD_REGION }}
        role-to-assume: ${{ env.AWS_S3_UPLOAD_ROLE_ARN }}
        role-session-name: ${{ env.AWS_S3_UPLOAD_SESSION }}
    - name: Build
      run : make package

    - name: Upload
      run: |
        aws s3 cp ./dist/zbrow.io.tar.gz "s3://github-artifacts-zeebrow/zbrow.io-website/latest-dev/"
        aws s3 cp ./dist/SHA256SUMS "s3://github-artifacts-zeebrow/zbrow.io-website/latest-dev/"

